CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE_USUARIO VARCHAR2(50) NOT NULL,
    CLAVE_ACCESO VARCHAR2(150) NOT NULL,
    ACTIVO NUMBER(1) DEFAULT 1,
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);


CREATE TABLE LIBRO (
    ID_LIBRO NUMBER PRIMARY KEY,
    TITULO VARCHAR2(200) NOT NULL,
    AUTOR VARCHAR2(150) NOT NULL,
    ANIO_PUBLICACION NUMBER(4),
    CANTIDAD_DISPONIBLE NUMBER DEFAULT 0,
    ACTIVO NUMBER(1) DEFAULT 1,
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

CREATE TABLE ESTUDIANTE (
    ID_ESTUDIANTE NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    APELLIDO VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(150) UNIQUE NOT NULL,
    ACTIVO NUMBER(1) DEFAULT 1,
    FECHA_REGISTRO DATE DEFAULT SYSDATE
);

CREATE TABLE PRESTAMO (
    ID_PRESTAMO NUMBER PRIMARY KEY,
    ID_LIBRO NUMBER NOT NULL,
    ID_ESTUDIANTE NUMBER NOT NULL,
    FECHA_PRESTAMO DATE DEFAULT SYSDATE,
    FECHA_DEVOLUCION DATE,
    DEVUELTO CHAR(1) DEFAULT 'N' CHECK (DEVUELTO IN ('S', 'N')),
    ACTIVO NUMBER(1) DEFAULT 1,
    CONSTRAINT FK_PRESTAMO_LIBRO FOREIGN KEY (ID_LIBRO)
        REFERENCES LIBRO(ID_LIBRO),
    CONSTRAINT FK_PRESTAMO_ESTUDIANTE FOREIGN KEY (ID_ESTUDIANTE)
        REFERENCES ESTUDIANTE(ID_ESTUDIANTE)
);


CREATE TABLE INVENTARIO (
    ID_INVENTARIO NUMBER PRIMARY KEY,
    ID_LIBRO NUMBER NOT NULL,
    TOTAL NUMBER DEFAULT 0,
    DISPONIBLES NUMBER DEFAULT 0,
    CONSTRAINT FK_INVENTARIO_LIBRO FOREIGN KEY (ID_LIBRO)
        REFERENCES LIBRO(ID_LIBRO)
);


INSERT INTO USUARIO (ID_USUARIO, NOMBRE_USUARIO, CLAVE_ACCESO)
VALUES (SEQ_USUARIO.NEXTVAL, 'BRYG25', 'contra90');

INSERT INTO USUARIO (ID_USUARIO, NOMBRE_USUARIO, CLAVE_ACCESO)
VALUES (SEQ_USUARIO.NEXTVAL, 'EKD25', 'contra21');

INSERT INTO USUARIO (ID_USUARIO, NOMBRE_USUARIO, CLAVE_ACCESO)
VALUES (SEQ_USUARIO.NEXTVAL, 'USER25', 'contra80');


INSERT INTO LIBRO (ID_LIBRO, TITULO, AUTOR, ANIO_PUBLICACION, CANTIDAD_DISPONIBLE)
VALUES (SEQ_LIBRO.NEXTVAL, 'Cien años de soledad', 'Gabriel García Márquez', 1967, 5);

INSERT INTO LIBRO (ID_LIBRO, TITULO, AUTOR, ANIO_PUBLICACION, CANTIDAD_DISPONIBLE)
VALUES (SEQ_LIBRO.NEXTVAL, 'Don Quijote de la Mancha', 'Miguel de Cervantes', 1605, 3);

INSERT INTO LIBRO (ID_LIBRO, TITULO, AUTOR, ANIO_PUBLICACION, CANTIDAD_DISPONIBLE)
VALUES (SEQ_LIBRO.NEXTVAL, 'La ciudad y los perros', 'Mario Vargas Llosa', 1963, 4);



INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, NOMBRE, APELLIDO, EMAIL)
VALUES (SEQ_ESTUDIANTE.NEXTVAL, 'Juan', 'Pérez', 'juan.perez@example.com');

INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, NOMBRE, APELLIDO, EMAIL)
VALUES (SEQ_ESTUDIANTE.NEXTVAL, 'María', 'Gómez', 'maria.gomez@example.com');

INSERT INTO ESTUDIANTE (ID_ESTUDIANTE, NOMBRE, APELLIDO, EMAIL)
VALUES (SEQ_ESTUDIANTE.NEXTVAL, 'Luis', 'Ramírez', 'luis.ramirez@example.com');


INSERT INTO PRESTAMO (ID_PRESTAMO, ID_ESTUDIANTE, ID_LIBRO, FECHA_PRESTAMO, DEVUELTO)
VALUES (SEQ_PRESTAMO.NEXTVAL, 1, 1, SYSDATE, 'N');

INSERT INTO PRESTAMO (ID_PRESTAMO, ID_ESTUDIANTE, ID_LIBRO, FECHA_PRESTAMO, DEVUELTO)
VALUES (SEQ_PRESTAMO.NEXTVAL, 2, 2, SYSDATE, 'N');

INSERT INTO PRESTAMO (ID_PRESTAMO, ID_ESTUDIANTE, ID_LIBRO, FECHA_PRESTAMO, FECHA_DEVOLUCION, DEVUELTO)
VALUES (SEQ_PRESTAMO.NEXTVAL, 3, 3, SYSDATE - 10, SYSDATE - 2, 'S');

INSERT INTO PRESTAMO (ID_PRESTAMO, ID_ESTUDIANTE, ID_LIBRO, FECHA_PRESTAMO, DEVUELTO)
VALUES (SEQ_PRESTAMO.NEXTVAL, 1, 2, SYSDATE, 'N');


INSERT INTO INVENTARIO (ID_INVENTARIO, ID_LIBRO, TOTAL, DISPONIBLES)
VALUES (SEQ_INVENTARIO.NEXTVAL, 1, 5, 5);

INSERT INTO INVENTARIO (ID_INVENTARIO, ID_LIBRO, TOTAL, DISPONIBLES)
VALUES (SEQ_INVENTARIO.NEXTVAL, 2, 3, 3);

INSERT INTO INVENTARIO (ID_INVENTARIO, ID_LIBRO, TOTAL, DISPONIBLES)
VALUES (SEQ_INVENTARIO.NEXTVAL, 3, 4, 4);



SELECT * FROM LIBRO;
SELECT * FROM ESTUDIANTE;
SELECT * FROM PRESTAMO;
SELECT * FROM INVENTARIO;

-- Secuencia para usuarios
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_USUARIO;

-- Secuencia para libros
CREATE SEQUENCE SEQ_LIBRO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_LIBRO;

-- Secuencia para estudiantes
CREATE SEQUENCE SEQ_ESTUDIANTE START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_ESTUDIANTE;

-- Secuencia para inventario
CREATE SEQUENCE SEQ_INVENTARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Secuencia para préstamos
CREATE SEQUENCE SEQ_PRESTAMO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


------- TRIGGERS -------
create or replace NONEDITIONABLE TRIGGER trigg_prestamo_insert
AFTER INSERT ON PRESTAMO
FOR EACH ROW
BEGIN
    IF :NEW.devuelto = 'N' THEN
        UPDATE INVENTARIO
        SET DISPONIBLES = DISPONIBLES - 1
        WHERE ID_LIBRO = :NEW.id_libro;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trigg_prestamo_update
AFTER UPDATE OF devuelto ON PRESTAMO
FOR EACH ROW
BEGIN
    IF :OLD.devuelto = 'N' AND :NEW.devuelto = 'S' THEN
        UPDATE INVENTARIO
        SET DISPONIBLES = DISPONIBLES + 1
        WHERE ID_LIBRO = :NEW.id_libro;


    ELSIF :OLD.devuelto = 'S' AND :NEW.devuelto = 'N' THEN
        UPDATE INVENTARIO
        SET DISPONIBLES = DISPONIBLES - 1
        WHERE ID_LIBRO = :NEW.id_libro;
    END IF;
END;
/

CREATE OR REPLACE TRIGGER trigg_prestamo_before_update
BEFORE UPDATE OF devuelto ON PRESTAMO
FOR EACH ROW
BEGIN
    IF :OLD.devuelto = 'S' AND :NEW.devuelto = 'N' THEN
        :NEW.fecha_devolucion := NULL;
    ELSIF :OLD.devuelto = 'N' AND :NEW.devuelto = 'S' THEN
        :NEW.fecha_devolucion := SYSDATE;
    END IF;
END;
/